# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'japan_terebi-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for japan_terebi-iOS

  target 'japan_terebi-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'japan_terebi-iOSUITests' do
    # Pods for testing
  end

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # https://firebase.google.com/docs/ios/setup#available-pods
end
